In [1]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn 

In [2]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
[4, 2, 10.2]

[4, 2, 10.2]

In [7]:
import numpy as np 


In [30]:
import numpy as np

A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 2],
              [-3, 4]])

result = A + B
print(result)


[[ 3  1]
 [-3  7]]


In [ ]:
import numpy as np

A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 2],
              [-3, 4]])

AB = np.dot(A, B)     

print(AB)


[[ 5  0]
 [-9 12]]


In [33]:
import numpy as np

A = np.array([[2, -1],
              [0, 3]])

B = np.array([[1, 2],
              [-3, 4]])

AB = 3*A + 2*B     # or A @ B

print(AB)


[[ 8  1]
 [-6 17]]


In [36]:
import numpy as np
import numpy.linalg as LA  

A = np.array([[2, -1],
              [0, 3]])

det_A = LA.det(A)
print("Determinant of A:", det_A)
A_inv = LA.inv(A)
print("Inverse of A:\n", A_inv)


Determinant of A: 6.0
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


In [37]:
import numpy as np
C = np.array([[4, 1],
              [-2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix C:")
print(C)
print("\nEigenvalue (first):")
print(eigenvalues[0])
print("\nCorresponding Eigenvector:")
print(eigenvectors[:, 0])

Matrix C:
[[ 4  1]
 [-2  1]]

Eigenvalue (first):
3.0

Corresponding Eigenvector:
[ 0.70710678 -0.70710678]


Well question no 4 I copied from AI

In [38]:
import numpy as np
X = np.array([[1, 4, 1.5, 100],
              [1, 6, 2.0, 150]])
y = np.array([20, 30])
beta = np.linalg.pinv(X.T @ X) @ X.T @ y
x3 = np.array([1, 8, 3.0, 200])
price_car3 = x3 @ beta
print("Predicted price for Car 3:", price_car3)

Predicted price for Car 3: 40.000798658250474
